### ISSUE TITLE
Missing API (How do I install)

### ISSUE THREAD

**Issue by CuteSockHunter** [Lakifume/SotnKindAndFair#2]
Greetings.

I have a legit ISO copy of castlevania sympthony of the night. I don't understand how to install it. I extract the KindAndFair rar on the same folder as the ISO, but when I run it it says api-ms-win-core-path-l1-1-0.dll is missing from my computer.

How do I install? This is on PS1 emulator, windows 7.

Thank you.

**Comment by Lakifume** [comment]
Oh unfortunately Python dropped support for Windows 7 a bit ago, only Windows 10 and later can run Python programs like this one now.

**Comment by CuteSockHunter** [comment]
> 

Thank you. I will update to windows 10 sometime in the future. Closing the thread.
