### ISSUE TITLE
Question: Compatibility with Quality Hack

### ISSUE THREAD

**Issue by RavenMacDaddy** [Lakifume/SotnKindAndFair#3]
Are you aware if the Kind and Fair mod is compatible with the [Quality Hack](https://www.romhacking.net/hacks/3606/)?

The feature set doesn't seem to clash, but you tell me.

**Comment by Lakifume** [comment]
Yes they are compatible, you can even place the Quality Hack ppf inside the KindAndFair\Data\Symphony\Patches folder and it'll get applied automatically when running the program.
