### ISSUE TITLE
Bug?: Asking me to update even though it should be the latest release

### ISSUE THREAD

**Issue by RavenMacDaddy** [Lakifume/SotnKindAndFair#7]
So the version is 1.5.6, latest at the time of writing when I check this repository;

![image](https://user-images.githubusercontent.com/67732686/192134714-d0bfb61f-97d3-43ba-9c36-cc87ed40cbbe.png)

…but the app shows me this:

![image](https://user-images.githubusercontent.com/67732686/192134659-30774fff-a061-49b0-9a96-aaaba7f98775.png)

For reference, I created a manifest for Scoop (commonly known as a package manager), keeping the app in line with the repository;

![image](https://user-images.githubusercontent.com/67732686/192134772-5400d8b8-66db-45f4-a1c5-8819b2f6a581.png)

![image](https://user-images.githubusercontent.com/67732686/192134681-71cad7a4-4e8d-46a4-85ad-e83fc2a617d6.png)

**Comment by Lakifume** [comment]
If you open the mod's config.ini in a text editor what does the sVersion entry say ?

**Comment by RavenMacDaddy** [comment]
`sVersion = 1.5.2` – so apparently a persisted config doesn't change that value.

Is that something that can adapt? It would make the user able to persist their config file, e.g., for installation with a package manager.

**Comment by Lakifume** [comment]
No actually I see the issue now, when the program auto updated it failed to close itself to open the new one so when you closed it manually it overwrote the new config with the old version number. Will fix in next update, for now you can fix it by either downloading manually or setting that config entry back to 1.5.6.

**Comment by RavenMacDaddy** [comment]
I see, appreciate it, @Lakifume
