### ISSUE TITLE
Is there any feasible way to use your tool with the beloved fan translation of the JP version?

### ISSUE THREAD

**Issue by ChocoChopin** [Lakifume/SotnKindAndFair#8]
Unfortunately, the tool seems to hang at 0% when attempting to use it on the fan-translated ROM, which is itself based on the original JP release rather than the later NA release.

**Comment by Lakifume** [comment]
The japanese version if known to be internally different than the US one, which is also why the Sotn randomizer isn't compatible with it either. Not much I can do there
